Fix French grammar and punctuation
rugk/mastodon-simplified-federation pull request #108
Opened 2023-04-27 19:08 UTC by amcwb

Some punctuation was incorrectly used and there were a few meaning / grammar changes.

2023-04-29 09:47 UTC, rugk commented
Hi @amcwb,
first of all, thanks for your first contribution to this project! :tada: :+1: 🏅
I hope you'll like this project and enjoy hacking on it… :smiley:

Requesting a potential review from @PoorPocketsMcNeuHold, @le-jun and Antonin Curtit (@AntoninCurtit). Unless there are objections, this will be merged soon.

Please subscribe to #40 to get notified for new updates on translations etc. :smiley:

2023-04-29 12:48 UTC, le-jun reviewed
Ok pour les deux segments modifiés. Pour du reste, pourquoi avoir remplacé les apostrophes typographiques par des apostrophes droites ?

2023-04-29 12:48 UTC, le-jun commented on src/_locales/fr/messages.json
> +    "message": "Certaines options sont gérées par l'administrateur système et ne peuvent pas être modifiées.",
Ok

2023-04-29 12:48 UTC, le-jun commented on src/_locales/fr/messages.json
> +    "message": "Cette option est désactivée par votre administrateur système.",
Ok

2023-04-29 12:51 UTC, amcwb commented
Parce que c'est plus typique d'utiliser l apostrophe droite. La plupart des applications utilisent cette apostrophe, ainsi que le clavier Apple et Android.

C'est aussi plus lisible.

2023-05-01 20:43 UTC, amcwb commented
J'avais mal regardé le texte, mais sur ce point : il semble qu'on utilise https://codepoints.net/U+00B4 mais n'est-ce pas vrai qu'on devrait donc utiliser https://codepoints.net/U+2019 (ou https://codepoints.net/U+0027, ce que vous avez utilisé dans votre réponse - l'apostrophe "typique"). On les change ?

2023-05-01 21:34 UTC, le-jun commented
> On les change ?

« les » concerne quoi ? Si c'est pour les layouts de claviers je plaide pour et prône déjà l'usage du Bépo au quotidien.

> Parce que c'est plus typique d'utiliser l apostrophe droite. La plupart des applications utilisent cette apostrophe, ainsi que le clavier Apple et Android.
> C'est aussi plus lisible.

Dans le cadre d'un parsing logiciel peut-être, là il me semble qu'on soit exclusivement sur un usage « esthétique » destiné à être lu par des personnes. Peut-importe que ce soit plus typique, ça doit seulement être fonctionnel, et dans ce cadre je vois pas d'élément qui justifierait d'utiliser la version des apostrophes droites. Y a pas à avoir honte d'utiliser des petites subitilités typographiques, d'autant plus lorsque destiné au public adéquat c'est une forme d'accessibilité humaine. Si jamais cette forme était amenée à être obsolète alors je m'adapterais sans soucis, le fait est que ça reste le standard en France métropolitaine – Je sais pas pour les autres territoires francophones.

2023-06-20 14:00 UTC, rugk commented
@amcwb If you need any pointers/help or have questions, feel free to ask.

AFAIK you have not yet applied any suggestions of contributors here. You can just do that online and in the same PR – you do not need to open a new one.

I would like to do a maintenance release soon, so I would like to have this merged if possible.
Another thing you could do is add maintainers with write access to [your fork of this repo](https://github.com/amcwb/mastodon-simplified-federation/). You _should_ be [be able to do this on this page here](https://github.com/amcwb/mastodon-simplified-federation/settings/access). Then they can also push changes into that branch.

2023-07-23 17:56 UTC, rugk commented
So the proposal has been declined.. should this still be merged? If so, what parts?

Please adjust it accordingly… thanks. :slightly_smiling_face:

2023-08-02 19:39 UTC, rugk commented
You mean https://github.com/amcwb/mastodon-simplified-federation/pull/1? So yeah @amcwb is that okay?

Otherwise I guess you could also create that PR against this repo here and it should contain the same changes/and credits, i.e. I can merge it then.

2023-08-02 19:40 UTC, rugk requested changes

2023-08-02 19:40 UTC, rugk commented on src/_locales/fr/messages.json
> +    "message": "PoorPocketsMcNewHold, le-jun et amcwb/stars",
In any case, I guess you'd need to adjust the credits here then?

And if you are good, you can adjust the `CONTRIBUTORS.md` file in the root.

2023-08-02 21:35 UTC, amcwb commented
Hey guys. I've merged that in - sorry for ghosting this PR a little I've been very prioritised on my work!

If that's all good and there's no more changes to request then I guess my work here is done @rugk.

Let me know if there's anything else!

2023-08-03 20:50 UTC, rugk approved these changes

2023-08-03 20:50 UTC, merged